name: saps5app
description: "SAES5 Android App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  
  # --- AJOUT DE LA LOCALISATION ---
  flutter_localizations:
    sdk: flutter
  # -------------------------------

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  provider: ^6.1.5+1
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  go_router: ^17.0.1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.6.1
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
